### ISSUE TITLE
Issue on 2.1.56 Qt6 when clicking options while holding shift

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-Memberships/AnkiWeekendsAndHolidays#4]
> Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
> Platform: macOS-13.1-x86_64-i386-64bit
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-01-14 21:30:52
> Add-ons possibly involved: ⁨Weekends and Holidays⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.deckconf", line 118, in onConfChange
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 80, in repl
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 80, in repl
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 81, in repl
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/1222550498/deckoptions.py", line 71, in load_conf
>     f.DisableFW.setCheckState(c.get("weekends_disabled", 0))
> TypeError: setCheckState(self, Qt.CheckState): argument 1 has unexpected type 'int'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.deckbrowser", line 271, in <lambda>
>   File "aqt.deckbrowser", line 297, in _options
>   File "aqt.deckoptions", line 103, in display_options_for_deck_id
>   File "aqt.deckoptions", line 110, in display_options_for_deck
>   File "aqt.deckconf", line 43, in __init__
>   File "aqt.deckconf", line 77, in setupConfs
>   File "aqt.deckconf", line 94, in loadConfs
>   File "aqt.deckconf", line 114, in onConfChange
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 84, in repl
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 84, in repl
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 83, in repl
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/1222550498/deckoptions.py", line 77, in save_conf
>     c["weekends_disabled"] = int(f.DisableFW.checkState())
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'CheckState'

**Comment by AnKingMed** [comment]
@abdnh if you have time could you look into this?

**Comment by AnKingMed** [comment]
nevermind. I had two copies of the addon installed for some reason..
